routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UsersController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('/', HomeController::class);
Route::any('/users', [UsersController::class, 'index']);
Route::get('/users/:id', [UsersController::class, 'show'])->where('id', '[0-9]');
Route::post('/users/:id', [UsersController::class, 'edit'])->where('id', '[0-9]');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Carbon\Carbon;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'last_name',
        'middle_name',
        'iin',
        'birthday',
        'mobile_phone',
        'marital_status_id',
        'family_units',
        'disable_group',
        'education_id',
        'specialty',
        'work_experience_common',
        'work_experience_by_specialty',
        'prev_work_place_name',
        'current_work_place_name',
        'current_work_place_position',
        'work_status_id',
        'work_type_id',
        'needle_help',
        'some_note',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'needle_help' => 'array',
        'some_note' => 'array',
    ];

    protected $attributes = [
        'needle_help' => [],
        'some_note' => [],
    ];

    
    public function getFioAttribute()
    {
        return "{$this->last_name} {$this->name} {$this->middle_name}";
    }
    
    public function getAgeAttribute()
    {
        return Carbon::parse($this->birthday)->age;
    }

    public function user_addresses() 
    {
        return $this->hasMany(\App\Models\UserAddress::class);
    }
    
    public function user_categories() 
    {
        return $this->hasMany(\App\Models\UserDisabledCategory::class);
    }
    
    public function marital_status() 
    {
        return $this->hasOne('App\Models\MaritalStatus', 'id', 'marital_status_id');
    }
    
    public function work_status() 
    {
        return $this->hasOne('App\Models\WorkStatus', 'id', 'work_status_id');
    }
    
    public function work_type() 
    {
        return $this->hasOne('App\Models\WorkType', 'id', 'work_type_id');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\DisabledCategory;
use App\Models\Education;
use App\Models\MaritalStatus;
use App\Models\User;
use App\Models\WorkStatus;
use App\Models\WorkType;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $usersQuery = User::with(['user_addresses', 'user_categories', 'work_type', 'marital_status', 'work_status']); 
        
        $users = $usersQuery->get();
        
        $json = $request->json()->all();

        $disabledCategories = DisabledCategory::all();
        $workTypes = WorkType::all();
        $workStatuses = WorkStatus::all();
        $maritalStatuses = MaritalStatus::all();
        $educations = Education::all();

        if (count($json) > 0) {
            return view('users.table')
                ->with('users', $users)
                ;
        }

        return view('users.index')
            ->with('request', $request)
            ->with('users', $users)
            ->with('disabledCategories', $disabledCategories)
            ->with('workStatuses', $workStatuses)
            ->with('maritalStatuses', $maritalStatuses)
            ->with('educations', $educations)
            ->with('workTypes', $workTypes)
            ;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/index.blade.php
@extends('layouts.main')

@section('title', 'Users')

@section('content')

<div class="section">
    <div class="columns">
        <div class="column is-4">
            <label class="label" for="filters[iin]">ИИН</label>
            <div class="field">
                <div class="control">
                    <input class="input" name="filters[iin]" type="text" placeholder="ИИН">
                </div>
            </div>
        </div>
        <div class="column is-4">
            <label class="label" for="filters[disabled_category]">Категория</label>
            <div class="field">
                <div class="control">
                    <div class="select">
                        <select name="filters[disabled_category]">
                            @foreach ($disabledCategories as $category)
                                <option value="{{ $category->id }}">{{ $category->ru_name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="column is-4">
            <label class="label">Инвалидность</label>
            <div class="field">
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[disabled_group][]" value="1">
                        <span class="check is-info"></span>
                        <span class="control-label">1 Группа</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[disabled_group][]" value="2">
                        <span class="check is-info"></span>
                        <span class="control-label">2 Группа</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[disabled_group][]" value="3">
                        <span class="check is-info"></span>
                        <span class="control-label">3 Группа</span>
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class="columns">
        <div class="column">
            <h5 class="title is-4">Адрес</h5>
        </div>
    </div>
    <div class="columns">
        <div class="column is-2">
            <label class="label" for="filters[address][city]">Город</label>
            <div class="field">
                <div class="control">
                    <input class="input" name="filters[address][city]" type="text" placeholder="Город">
                </div>
            </div>
        </div>
        <div class="column is-2">
            <label class="label" for="filters[address][district]">Район</label>
            <div class="field">
                <div class="control">
                    <input class="input" name="filters[address][district]" type="text" placeholder="Район">
                </div>
            </div>
        </div>
        <div class="column is-2">
            <label class="label" for="filters[address][street]">Улица</label>
            <div class="field">
                <div class="control">
                    <input class="input" name="filters[address][street]" type="text" placeholder="Улица">
                </div>
            </div>
        </div>
    </div>
    <div class="columns">
        <div class="column is-4">
            <label class="label" for="filters[marital_status]">Семейное положение</label>
            <div class="field">
                @foreach ($maritalStatuses as $status)
                    <div class="control">
                        <label class="b-checkbox checkbox is-small">
                            <input type="checkbox" name="filters[marital_status][]" value="{{ $status->id }}">
                            <span class="check is-info"></span>
                            <span class="control-label">{{ $status->ru_name }}</span>
                        </label>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="column is-4">
            <label class="label" for="filters[education]">Образование</label>
            <div class="field">
                @foreach ($educations as $education)
                    <div class="control">
                        <label class="b-checkbox checkbox is-small">
                            <input type="checkbox" name="filters[education][]" value="{{ $education->id }}">
                            <span class="check is-info"></span>
                            <span class="control-label">{{ $education->ru_name }}</span>
                        </label>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="column is-4">
            <label class="label">Возраст</label>
            <div class="field">
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[ages][]" value="=<20">
                        <span class="check is-info"></span>
                        <span class="control-label">До 20 лет</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[ages][]" value=">=21|<=29">
                        <span class="check is-info"></span>
                        <span class="control-label">От 21 до 29 лет</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[ages][]" value=">=30|<=45">
                        <span class="check is-info"></span>
                        <span class="control-label">От 30 до 45 лет</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[ages][]" value=">=46|<=58">
                        <span class="check is-info"></span>
                        <span class="control-label">От 46 до 58 лет</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[ages][]" value=">=59|<=70">
                        <span class="check is-info"></span>
                        <span class="control-label">От 59 до 70 лет</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox">
                        <span class="check is-info"></span>
                        <span class="control-label">Произвольный период</span>
                    </label>
                    <div class="field is-grouped">
                        <div class="control">
                            <input class="input is-small" type="number" min="1" max="100" name="filters[ages][other][from]" placeholder="От">
                        </div>
                        <div class="control">
                            <input class="input is-small" type="number" min="1" max="100" name="filters[ages][other][to]" placeholder="До">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="columns">
        <div class="column is-4">
            <label class="label" for="filters[work_status]">Статус</label>
            <div class="field">
                @foreach ($workStatuses as $status)
                    <div class="control">
                        <label class="b-checkbox checkbox is-small">
                            <input type="checkbox" name="filters[work_status][]" value="{{ $status->id }}">
                            <span class="check is-info"></span>
                            <span class="control-label">{{ $status->ru_name }}</span>
                        </label>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="column is-4">
            <label class="label" for="filters[work_type]">Работа</label>
            <div class="field">
                @foreach ($workTypes as $work)
                    <div class="control">
                        <label class="b-checkbox checkbox is-small">
                            <input type="checkbox" name="filters[work_type][]" value="{{ $work->id }}">
                            <span class="check is-info"></span>
                            <span class="control-label">{{ $work->ru_name }}</span>
                        </label>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="column is-4">
            <label class="label">Стаж работы</label>
            <div class="field">
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[seniority][]" value="<1">
                        <span class="check is-info"></span>
                        <span class="control-label">До 1 года</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[seniority][]" value=">=1|<3">
                        <span class="check is-info"></span>
                        <span class="control-label">От 1 до 3 лет</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[seniority][]" value=">=3|<7">
                        <span class="check is-info"></span>
                        <span class="control-label">От 3 до 7 лет</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox" name="filters[seniority][]" value=">=7|<15">
                        <span class="check is-info"></span>
                        <span class="control-label">От 7 до 15 лет</span>
                    </label>
                </div>
                <div class="control">
                    <label class="b-checkbox checkbox is-small">
                        <input type="checkbox">
                        <span class="check is-info"></span>
                        <span class="control-label">Произвольный период</span>
                    </label>
                    <div class="field is-grouped">
                        <div class="control">
                            <input class="input is-small" type="number" min="1" max="50" name="filters[seniority][other][from]" placeholder="От">
                        </div>
                        <div class="control">
                            <input class="input is-small" type="number" min="1" max="50" name="filters[seniority][other][to]" placeholder="До">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='container has-text-centered'>
        <div class='columns is-mobile is-centered'>
            <div class='column is-12'>
                <div>
                    <h1 class='title'>Информация о пользователях</h1>
                    <hr>
                </div>
                <table class='table'>
                    <thead>
                        <tr>
                            <th>ФИО</th>
                            <th>ИИН</th>
                            <th>Категория</th>
                            <th>Возраст</th>
                            <th>Контактный телефон</th>
                            <th>Семейное положение</th>
                            <th>Адрес проживания</th>
                            <th>Статус</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    @include('users.table', ['users' => $users])
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/users/table.blade.php
<tbody>
    @foreach($users as $user)
        <tr>
            <td>{{ $user->fio }}</td>
            <td>{{ $user->iin }}</td>
            <td>
                @foreach($user->user_categories as $category)
                    {{ $category->ru_name }} <br />
                @endforeach
            </td>
            <td>{{ $user->age }}</td>
            <td>{{ $user->mobile_phone }}</td>
            <td>{{ $user->marital_status->ru_name }}</td>
            <td>{{ $user->address }}</td>
            <td>{{ $user->work_status->ru_name }}</td>
            <td><a href="/users/{{ $user->id }}" class="button is-success">Карточка пользователя</a></td>
        </tr>
    @endforeach
</tbody>